Assignment03/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :enrollments
  resources :students
  resources :sections
  resources :courses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Assignment03/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

Assignment03/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

Assignment03/app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <style type="text/css">
    input { text-align:right; }
    </style>
    <%= form.label :name %>
    <%= form.text_field :name, id: :course_name %>
  </div>

  <div class="field">
    <%= form.label :department %>
    <%= form.text_field :department, id: :course_department %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number, id: :course_number %>
  </div>

  <div class="field">
    <%= form.label :credit_hours %>
    <%= form.number_field :credit_hours, id: :course_credit_hours %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Assignment03/app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<div>
  <%= form_tag(courses_path, method: :get) do %>
    <%= label_tag(:query, "Search for:") %>
    <%= text_field_tag(:query) %>
    <%= submit_tag("Search") %>
  <% end %>
</div>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Department</th>
      <th>Number</th>
      <th>Credit hours</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.department %></td>
        <td><%= course.number %></td>
        <td><%= course.credit_hours %></td>
        <td padding: 25px><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div>
  <%= link_to 'New Course', new_course_path %>
</div>

Assignment03/app/views/courses/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<ol>
  <% @course.sections.each do |section| %>
    <li> <%= section.name %>
  <% end %>
</ol>

<p>
  <strong>Department:</strong>
  <%= @course.department %>
</p>

<p>
  <strong>Number:</strong>
  <%= @course.number %>
</p>

<p>
  <strong>Credit hours:</strong>
  <%= @course.credit_hours %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

Assignment03/app/views/enrollments/show.html.erb
<p>
  <strong>Section:</strong>
  <%= @enrollment.section.name %>
</p>

<p>
  <strong>Student:</strong>
  <%= @enrollment.student.name %>
</p>

<%= link_to 'Edit', edit_enrollment_path(@enrollment) %> |
<%= link_to 'Back', enrollments_path %>

Assignment03/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assignment03</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>
    a, th, td, h, h1, h2, div {
        padding-left: 7px;
    }
    </style>

    <nav class="navbar navbar-inverse">
      <ul class="nav">
        <li class="nav-link"><%= link_to 'Courses', courses_path, :class => 'navbar-link' %></li>
        <li class="nav-link"><%= link_to 'Enrollments', enrollments_path, :class => 'navbar-link' %></li>
        <li class="nav-link"><%= link_to 'Sections', sections_path, :class => 'navbar-link' %></li>
        <li class="nav-link"><%= link_to 'Students', students_path, :class => 'navbar-link' %></li>

      <% if user_signed_in? %>
        <li class="navbar-text">Logged in as <strong><%= current_user.email %></strong></li>
        <li class="nav-link"><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
        <li class="nav-link"><%= link_to 'Logout', destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
      <% else %>
        <li class="nav-link"><%= link_to 'Sign up', new_user_registration_path, :class => 'navbar-link'  %></li>
        <li class="nav-link"><%= link_to 'Login', new_user_session_path, :class => 'navbar-link'  %></li>
      <% end %>
      </ul>
    </nav>

 </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

Assignment03/app/views/sections/show.html.erb
<p>
  <strong>Course:</strong>
  <%= @section.course.name %>
</p>

<p>
  <strong>Semester:</strong>
  <%= @section.semester %>
</p>

<p>
  <strong>Number:</strong>
  <%= @section.number %>
</p>

<p>
  <strong>Room number:</strong>
  <%= @section.room_number %>
</p>

<p>
  <strong>Students:</strong>
  <ol>
  <% @section.students.each do |student| %>
    <li><%= student.name %></li>
  <% end %>
  </ol>
</p>

<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>

Assignment03/app/views/students/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Sections:</strong>
  <ol>
  <% @student.sections.each do |section| %>
    <li><%= section.name %></li>
  <% end %>
  </ol>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>