Assignment05/config/routes.rb
Rails.application.routes.draw do
  resources :enrollments
  resources :students
  resources :sections
  resources :courses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Assignment05/app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :section
  belongs_to :student
  validates :section, 	presence: true, 
						length: { maximum: 50, message: "must be less than 50 characters in length" }
  validates :student, 	presence: true, 
						length: { maximum: 50, message: "must be less than 50 characters in length" }
end

Assignment05/app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: [:show, :edit, :update, :destroy]

  # GET /enrollments
  # GET /enrollments.json
  def index
    if params[:query]
	  @enrollments = Enrollment.where("name like ?", "%#{params[:query]}%")
	else
      @enrollments = Enrollment.all
    end
  end

  # GET /enrollments/1
  # GET /enrollments/1.json
  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments
  # POST /enrollments.json
  def create
    @enrollment = Enrollment.new(enrollment_params)
	@enrollment.name = "#{@enrollment.section.name} #{" - "} #{@enrollment.student.name}"

    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully created.' }
        format.json { render :show, status: :created, location: @enrollment }
      else
        format.html { render :new }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrollments/1
  # PATCH/PUT /enrollments/1.json
  def update
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully updated.' }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1
  # DELETE /enrollments/1.json
  def destroy
    @enrollment.destroy
    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: 'Enrollment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enrollment_params
      params.require(:enrollment).permit(:section_id, :student_id)
    end
end

Assignment05/app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

Assignment05/app/views/enrollments/_form.html.erb
<%= form_with(model: enrollment, local: true) do |form| %>
  <% if enrollment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

      <ul>
      <% enrollment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :section_id %>
    <%= form.collection_select :section_id, Section.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :student_id %>
    <%= form.collection_select :student_id, Student.all, :id, :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Assignment05/app/views/enrollments/edit.html.erb
<h1>Editing Enrollment</h1>

<%= render 'form', enrollment: @enrollment %>

<%= link_to 'Show', @enrollment %> |
<%= link_to 'Back', enrollments_path %>

Assignment05/app/views/enrollments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enrollments</h1>

<%= form_tag(enrollments_path, method: :get) do %>
  <%= label_tag(:query, "Search for:") %>
  <%= text_field_tag(:query) %>
  <%= submit_tag("Search") %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Section</th>
      <th>Student</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enrollments.each do |enrollment| %>
      <tr>
        <td><%= enrollment.section.name %></td>
        <td><%= enrollment.student.name %></td>
        <td><%= link_to 'Show', enrollment %></td>
        <td><%= link_to 'Edit', edit_enrollment_path(enrollment) %></td>
        <td><%= link_to 'Destroy', enrollment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enrollment', new_enrollment_path %>

Assignment05/app/views/enrollments/new.html.erb
<h1>New Enrollment</h1>

<%= render 'form', enrollment: @enrollment %>

<%= link_to 'Back', enrollments_path %>

Assignment05/app/views/enrollments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Section:</strong>
  <%= @enrollment.section.name %>
</p>

<p>
  <strong>Student:</strong>
  <%= @enrollment.student.name %>
</p>

<%= link_to 'Edit', edit_enrollment_path(@enrollment) %> |
<%= link_to 'Back', enrollments_path %>