Assignment05/config/routes.rb
Rails.application.routes.draw do
  resources :enrollments
  resources :students
  resources :sections
  resources :courses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Assignment05/app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
  has_many :enrollments, dependent: :destroy
  has_many :students, through: :enrollments, dependent: :destroy
  def name
    "#{course.name} #{" - Section "} #{number} #{" - "} #{semester}"
  end
  validates :course, 		presence: true, 
							length: { maximum: 50, message: "must be less than 50 characters in length" }
  validates :semester, 		presence: true, 
                            format: { with: /\A\w{4,6}\s\d{4}\z/, message: "should be in the form [Season] [Year]" },
							length: { maximum: 11, message: "must be less than 11 characters in length" }
  validates :number, 		presence: true,
                            format: { with: /\A[0-9]/, message: "only allows numbers" },
							numericality: { greater_than_or_equal_to: 1, 
							                less_than_or_equal_to: 4, 
											message: "must be between 1 and 4" },
							length: { is: 1 }
  validates :room_number, 	presence: true, 
                            format: { with: /\A[0-9]/, message: "only allows numbers" },
							numericality: { greater_than_or_equal_to: 100, 
							                less_than_or_equal_to: 600, 
											message: "must be between 100 and 600" },
							length: { is: 3 }
end

Assignment05/app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]

  # GET /sections
  # GET /sections.json
  def index
    if params[:query]
	  @sections = Section.where("name like ?", "%#{params[:query]}%").where("semester like ?", "%#{params[:query]}%")
	else
      @sections = Section.all
    end
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)
	@section.name = "#{@section.course.name} #{" - Section "} #{@section.number} #{" - "} #{@section.semester}"
	
    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:course_id, :semester, :number, :room_number, :query)
    end
end

Assignment05/app/helpers/sections_helper.rb
module SectionsHelper
end

Assignment05/app/views/sections/_form.html.erb
<%= form_with(model: section, local: true) do |form| %>
  <% if section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :course_id %>
    <%= form.collection_select :course_id, Course.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :semester %>
    <%= form.text_field :semester, id: :section_semester %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number, id: :section_number %>
  </div>

  <div class="field">
    <%= form.label :room_number %>
    <%= form.number_field :room_number, id: :section_room_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Assignment05/app/views/sections/edit.html.erb
<h1>Editing Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', sections_path %>

Assignment05/app/views/sections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sections</h1>

<%= form_tag(sections_path, method: :get) do %>
  <%= label_tag(:query, "Search for:") %>
  <%= text_field_tag :query, params[:query] %>
  <%= submit_tag("Search") %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Course</th>
      <th>Semester</th>
      <th>Number</th>
      <th>Room number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.course.name %></td>
        <td><%= section.semester %></td>
        <td><%= section.number %></td>
        <td><%= section.room_number %></td>
        <td><%= link_to 'Show', section %></td>
        <td><%= link_to 'Edit', edit_section_path(section) %></td>
        <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Section', new_section_path %>

Assignment05/app/views/sections/new.html.erb
<h1>New Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Back', sections_path %>

Assignment05/app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course:</strong>
  <%= @section.course.name %>
</p>

<p>
  <strong>Semester:</strong>
  <%= @section.semester %>
</p>

<p>
  <strong>Number:</strong>
  <%= @section.number %>
</p>

<p>
  <strong>Room number:</strong>
  <%= @section.room_number %>
</p>

<p>
  <strong>Students:</strong>
  <ol>
  <% @section.students.each do |student| %>
    <li><%= student.name %></li>
  <% end %>
  </ol>
</p>

<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>